First task
zaureshazh/java-fundamentals-tasks pull request #1
Opened 2021-02-24 08:50 UTC by zaureshazh

add first task

2021-02-24 08:59 UTC, gavrillina requested changes

2021-02-24 08:59 UTC, gavrillina commented on MainTask/src/main/java/FirstTask.java
> +        System.out.print("Enter your name: ");
if we enter several names?

2021-02-25 12:46 UTC, zaureshazh commented on MainTask/src/main/java/FirstTask.java
> +        System.out.print("Enter your name: ");
kindly check fixes, please

2021-02-25 12:46 UTC, zaureshazh commented on MainTask/src/main/java/FirstTask.java
> +        System.out.print("Enter your name: ");
> if we enter several names?

kindly check fixes, please

2021-02-26 12:06 UTC, merged